### ISSUE TITLE
Ready for release?

### ISSUE THREAD

**Issue by docwilmot** [backdrop-contrib/aggregator#1]
Is this ready?

**Comment by jlfranklin** [comment]
I'm able to use it to import from five different geek, news, and open source publications.  This confirms it is minimally functional.  I haven't looked into the code to see if it still uses `drupal_*()` functions.

I'd like to see a full release of this, too.

**Comment by jenlampton** [comment]
It seems ready, working great for me!

**Comment by sillygwailo** [comment]
I merged @jenlampton's pull request, and created an official release! Can we get this as a project on BackdropCMS.org?

**Comment by jenlampton** [comment]
The project should appear on b.org less than 5 seconds after the release was created...

**Comment by jenlampton** [comment]
Hm...  https://github.com/backdrop-contrib/aggregator/releases/tag/1.x-1.0.0 looks correct, maybe somethings up with the packager? checking...

**Comment by jenlampton** [comment]
Well, the packager worked for https://github.com/backdrop-contrib/borg/releases/tag/1.x-1.1.14.  Let's delete the release and try again?

**Comment by jenlampton** [comment]
Aha! this time we get a packaging error: https://github.com/backdrop-contrib/aggregator/releases/tag/1.x-1.0.0

The problems are documented in the attached file `PACKAGING_ERROR_LOG.txt`. It looks like we need to add a `type = module` line to the top of the `.info` file :)

Here's a PR: https://github.com/backdrop-contrib/aggregator/pull/7

**Comment by sillygwailo** [comment]
Merged! And that created the project at https://backdropcms.org/project/aggregator Let's call this done.
